// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourGT.DataAccess.EFCore;

#nullable disable

namespace YourGT.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(YourGTDbContext))]
    [Migration("20241113143324_MigrationV2")]
    partial class MigrationV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("YourGT.Shared.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Completed");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("Semesters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Semesters");

                    b.HasKey("Id");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("Value");

                    b.Property<int>("WeightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WeightId");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("EducationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Weight", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7, 5)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Weights", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "100%",
                            Value = 1m
                        },
                        new
                        {
                            Id = 2,
                            Name = "75%",
                            Value = 0.75m
                        },
                        new
                        {
                            Id = 3,
                            Name = "66.7%",
                            Value = 0.66667m
                        },
                        new
                        {
                            Id = 4,
                            Name = "50%",
                            Value = 0.5m
                        },
                        new
                        {
                            Id = 5,
                            Name = "33.3%",
                            Value = 0.33334m
                        },
                        new
                        {
                            Id = 6,
                            Name = "25%",
                            Value = 0.25m
                        },
                        new
                        {
                            Id = 7,
                            Name = "20%",
                            Value = 0.2m
                        },
                        new
                        {
                            Id = 8,
                            Name = "90%",
                            Value = 0.9m
                        },
                        new
                        {
                            Id = 9,
                            Name = "80%",
                            Value = 0.8m
                        },
                        new
                        {
                            Id = 10,
                            Name = "60%",
                            Value = 0.6m
                        },
                        new
                        {
                            Id = 11,
                            Name = "40%",
                            Value = 0.4m
                        },
                        new
                        {
                            Id = 12,
                            Name = "10%",
                            Value = 0.1m
                        },
                        new
                        {
                            Id = 13,
                            Name = "1000%",
                            Value = 10m
                        },
                        new
                        {
                            Id = 14,
                            Name = "500%",
                            Value = 5m
                        },
                        new
                        {
                            Id = 15,
                            Name = "300%",
                            Value = 3m
                        },
                        new
                        {
                            Id = 16,
                            Name = "200%",
                            Value = 2m
                        });
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Grade", b =>
                {
                    b.HasOne("YourGT.Shared.Entities.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourGT.Shared.Entities.Weight", "Weight")
                        .WithMany("Grades")
                        .HasForeignKey("WeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.HasOne("YourGT.Shared.Entities.Education", "Education")
                        .WithMany("Subjects")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Education", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Weight", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
