// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourGT.DataAccess.EFCore;

#nullable disable

namespace YourGT.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(YourGTDbContext))]
    partial class YourGTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("YourGT.Shared.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Completed");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("Semesters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Semesters");

                    b.HasKey("Id");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("Value");

                    b.Property<int>("WeightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WeightId");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("EducationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Weight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7, 5)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Weights", (string)null);
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Grade", b =>
                {
                    b.HasOne("YourGT.Shared.Entities.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourGT.Shared.Entities.Weight", "Weight")
                        .WithMany("Grades")
                        .HasForeignKey("WeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.HasOne("YourGT.Shared.Entities.Education", "Education")
                        .WithMany("Subjects")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Education", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("YourGT.Shared.Entities.Weight", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
